[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn medihelp.wsgi"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1
