# Generated by Django 5.2 on 2025-05-02 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skindiagnosis',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Skin Diagnoses'},
        ),
        migrations.AlterField(
            model_name='skindiagnosis',
            name='diagnosis',
            field=models.JSONField(blank=True, help_text='Structured analysis results', null=True),
        ),
        migrations.AlterField(
            model_name='skindiagnosis',
            name='image',
            field=models.ImageField(help_text='Upload image of skin condition', upload_to='skin_diagnosis/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='skindiagnosis',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='skindiagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
    ]
