# Generated by Django 5.2 on 2025-05-02 04:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('opening_hours', models.JSONField(default=dict)),
            ],
        ),
    ]
