# Generated by Django 5.2 on 2025-05-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_chatbot_cha_session_24e989_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
