# Generated by Django 5.2 on 2025-04-29 17:08

import django.db.models.deletion
import firstaid.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptoms', '0002_alter_symptomcheck_ai_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the instruction', max_length=200)),
                ('steps', models.JSONField(help_text="JSON array of steps e.g., ['Step 1', 'Step 2']", validators=[firstaid.validators.validate_json_array])),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.condition')),
            ],
        ),
        migrations.CreateModel(
            name='HomeRemedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.JSONField(help_text="JSON array of ingredients e.g., ['Honey', 'Lemon']", validators=[firstaid.validators.validate_json_array])),
                ('preparation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', models.ManyToManyField(to='symptoms.symptom')),
            ],
        ),
    ]
