# Generated by Django 5.2 on 2025-04-30 06:51

import education.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptoms', '0002_alter_symptomcheck_ai_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, help_text='Short preview text (max 150 chars)', max_length=150)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='Comma-separated list of tags', validators=[education.validators.validate_string_list])),
                ('cover_image', models.URLField(blank=True, help_text='URL to cover image (16:9 aspect ratio recommended)')),
                ('related_conditions', models.ManyToManyField(blank=True, to='symptoms.condition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(help_text='Full YouTube URL (e.g. https://youtube.com/watch?v=ID)', validators=[education.validators.validate_youtube_url])),
                ('duration_minutes', models.PositiveSmallIntegerField(help_text='Duration in minutes')),
                ('related_symptoms', models.ManyToManyField(blank=True, to='symptoms.symptom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
