# Generated by Django 5.2 on 2025-05-03 08:06

import education.models
import education.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_article_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL to cover image (16:9 aspect ratio recommended)', validators=[education.validators.validate_image_url]),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=education.models.Article.default_tags, help_text="List of tag strings, e.g., ['tag1', 'tag2']", validators=[education.validators.validate_string_list]),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(help_text='Duration in minutes (max 600 minutes / 10 hours)', validators=[education.validators.validate_duration_minutes]),
        ),
    ]
