# Generated by Django 5.2 on 2025-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_alter_symptomcheck_ai_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
